### PR TITLE
#4 added new hashing patches to enhance the password hashing algorithms in database

### PR DESCRIPTION
**Pull request by ritishbhardwaj**

### CODE REVIEW

**Comment by ritishbhardwaj** [comment]
kindly merge this useful commit
@EH-GD-MOHIT21

**Comment by ritishbhardwaj** [comment]
can we talk in respect to this additionality in code base
is this useful or not?
should i need to add more or not?

**Comment by EH-GD-MOHIT21** [comment]
Hey Ritish!

I just want to know how much experience you've in django are you a beginner?
I've a small task for you if you want to help.

Thanks & Regards
Mohit

**Comment by ritishbhardwaj** [comment]
kinda beginner but have made some small projects in hackathons.
yes ofcourse, i am ready to take any task

**Comment by ritishbhardwaj** [comment]
hi @EH-GD-MOHIT21 
could you please tell me how may i help you

**Comment by EH-GD-MOHIT21** [comment]
Hey Ritish!

Can you provide your email address for further communication?

Thanks

**Comment by ritishbhardwaj** [comment]
ritishbhardwaj02@gmail.com
Kindly consider this email for further communication

**Pull request closed without merging**
